### ISSUE TITLE
[Ver 12.0] account_chart_template.py not updated to v12?

### ISSUE THREAD

**Issue by NahuelVarela** [ingadhoc/argentina-sale#34]
Cuando se selecciona el plan contable, la aplicacion falla con: 

> _load_template() takes from 2 to 5 positional arguments but 6 were given

En la V12 de account_chart_template.py el codigo es:

```
@api.multi
    def _load_template(self, company, code_digits=None, transfer_account_id=None, account_ref=None, taxes_ref=None):
        self.ensure_one()
        if company.localization:
            self.generate_sale_checkbook(company)

        return super(AccountChartTemplate, self)._load_template(company, code_digits, account_ref, taxes_ref)
```

Esto se debe a que en la V12 chart_template.py acepta un maximo de 5 parametros:

`def _load_template(self, company, code_digits=None, account_ref=None, taxes_ref=None):`

Mientras que en la V11 acepta 6 paremetros:

` def _load_template(self, company, code_digits=None, transfer_account_id=None, account_ref=None, taxes_ref=None):`

Borrando "transfer_account_id=None" soluciona el problema pero no se si esto es expected.

**Comment by sotolucas** [comment]
Hola @NahuelVarela .
Muchas gracias por reportar el issue.
Estamos al tanto del mismo y nos encontramos trabajando para resolverlo.
